name: TexasHoldem_kotlin
version: ${version}
main: ltotj.minecraft.texasholdem_kotlin.Main
api-version: '1.21'
depend:
  - Vault
commands:
  poker:
    usage: "/poker help で使い方を確認しましょう"
  sng:
    description: Sit and Go tournament commands
    usage: "/sng <start|join|leave|rating|top|help>"
    aliases: [sitandgo]

permissions:
  poker.admin:
    default: op
  poker.player:
    default: true
